### ISSUE TITLE
постоянная ссылка на последнюю версию правил

### ISSUE THREAD

**Issue by whoizit** [Zalexanninev15/NoADS_RU#1]
Вам следует оставить одну, последнюю версию файла в репозитории и использовать тегирование версий в git вместо копирования файлов в репозитории

**Comment by 1nfdev** [comment]
Полностью поддерживаю. Человек не умеет пользоваться git и не понимает зачем он нужен.

@Zalexanninev15 Я не смеюсь над вами, но был бы рад, если вы ознакомились с базовыми операциями в git.
Также рекомендую поставить [github CLI](cli.github.com), чтобы делать именно github-теги, а не git-теги. Так как они по разному отображаются на гитхабе.

**Comment by Zalexanninev15** [comment]
Примерно, как я понял, то что нужно и сделал
