### ISSUE TITLE
Не работает на ADBlock plus

### ISSUE THREAD

**Issue by mickhaorex** [Zalexanninev15/NoADS_RU#10]
При попытке импортировать в chrome и firefox
`https://raw.githubusercontent.com/Zalexanninev15/NoADS_RU/main/ads_list.txt`
в ADBlock plus, показывает такую ошибку:
![screen](https://github.com/Zalexanninev15/NoADS_RU/assets/99164289/48b86855-4734-4f58-926b-43025d2c72a5)

**Comment by Zalexanninev15** [comment]
Здравствуйте. Да, действительно, проблема присутствует. Могу посоветовать скопировать текст из самого файла списка https://raw.githubusercontent.com/Zalexanninev15/NoADS_RU/main/ads_list.txt и вставить его в поле Мой список фильтров и нажать Enter. Через некоторое время фильтры должны будут примениться.
![image](https://github.com/Zalexanninev15/NoADS_RU/assets/51060911/a8f1ec07-f60a-494e-a0f8-950d132d54d9)

**Comment by mickhaorex** [comment]
И так не добавляется:

https://github.com/Zalexanninev15/NoADS_RU/assets/99164289/9e18ac34-00fc-4152-8d9e-1fa54b14d3f1




В любом случае, хотелось бы онлайн обновление. Ваши фильтры весьма хороши.

P.S. Извиняюсь за качество видео, программа скриншотер лучше не может.

**Comment by Zalexanninev15** [comment]
Нужно открыть саму raw-ссылку на список `https://raw.githubusercontent.com/Zalexanninev15/NoADS_RU/main/ads_list.txt` и с помощью Ctrl+A выделить всё и скопировать в это поле. Потом нажать Enter и подождать немного (может быть нагрузка на CPU). Потом могут появляться предупреждения из-за большого количества фильтров, не останавливаем работу расширения и пытаемся перейти в другие разделы слева, а потом обновляем страницу с настройками. Теперь браузер должен отвиснуть и все фильтры будут добавлены.

**Comment by mickhaorex** [comment]
Спасибо. Все отлично работает:
![CGcROsHj](https://github.com/Zalexanninev15/NoADS_RU/assets/99164289/988517cc-515c-41d9-b275-d4c1a3d6057c)
![mXzebQPW](https://github.com/Zalexanninev15/NoADS_RU/assets/99164289/9c904734-1d40-4d9e-a5e1-5f857edf1a71)
