### ISSUE TITLE
некоректная ссылка 'Список с блокировками'

### ISSUE THREAD

**Issue by whoizit** [Zalexanninev15/NoADS_RU#2]
как я понимаю она должна вести на файл, а не на страницу
правильная ссылка - https://raw.githubusercontent.com/Zalexanninev15/NoADS_RU/master/ads_list.txt

**Comment by Zalexanninev15** [comment]
Неа, в принципе я так и задумал. Нажимаешь Raw -> Сохранить как, а потом импортируешь текстовик в нужное расширение. Мне так удобнее, а кому надо - можно нажать Raw и скопировать весь текст.

**Comment by whoizit** [comment]
а зачем импортировать. Просто добавляешь URL в µBlock и оно само обновляется
![2020-08-28_00:56:58_1187x292_grim](https://user-images.githubusercontent.com/359276/91499011-68a5fa80-e8c9-11ea-9266-354ec7459eab.png)

**Comment by Zalexanninev15** [comment]
Ух-ты, спасибо, теперь буду знать. Сейчас поправлю

**Comment by whoizit** [comment]
"Файл" всё-таки должен вести на файл, а не на страницу гитхаба, логическая ошибка

**Comment by Zalexanninev15** [comment]
А как добавить ссылку на скачивание файла? Я кроме "Сохранить как" не знаю как сделать🙁

**Comment by whoizit** [comment]
На мой взгляд, прямо сейчас у тебя всё сделано правильно. 
Если тебе нужно скопировать ссылку на файл, ты нажимаешь ПКМ на ссылке "Список с блокировками" и Copy Link Location (в Firefox). Если тебе нужно сохранить файл, то ты нажимаешь ПКМ и Save Link As. либо просто кликаешь на файл, чтоб он открылся на странице и выбераешь в меню браузера Save Page As. либо копируешь эту же ссылку и скачиваешь через wget или curl

**Comment by Zalexanninev15** [comment]
Хорошо. Спасибо за то что указали на мои недочёты, я так понял мне есть куда стремиться по развитию своих репозиториев.

**Comment by whoizit** [comment]
Если оформить ссылку в таком виде, то она должна открывать окошко с автоматическим добавлением ссылки на правила в настройки блокировщика рекламы (работает с adblock plus и ublock)
ссылка такого вида:
`[Подписка](abp:subscribe?location=https://github.com/Zalexanninev15/NoADS_RU/raw/master/ads_list.txt&title=NoADS_RU)` - не будет работать в Markdown на гитхабе, работает в HTML

или так, должно работать на гитхабе
`[Подписка](https://subscribe.adblockplus.org/?location=https://github.com/Zalexanninev15/NoADS_RU/raw/master/ads_list.txt&title=NoADS_RU)`

**Comment by Zalexanninev15** [comment]
Сделал, но у меня без VPN не работает, поэтому предупреждение добавил на всякий случай

**Comment by whoizit** [comment]
Работает, но некорректно добавляется Title, вероятно надо добавить в начало файла мета данные
```
[Adblock Plus 2.0]
! Title: NoADS_RU
```

**Comment by whoizit** [comment]
поменяй URL в ссылке на https://raw.githubusercontent.com/Zalexanninev15/NoADS_RU/master/ads_list.txt
иначе работать не хочет. Хотя на примере другого списка работало
