### ISSUE TITLE
конфликт со SponsorBlock

### ISSUE THREAD

**Issue by KVAnton-WEB** [Zalexanninev15/NoADS_RU#3]
www.youtube.com##tbody - Блокирует [SponsorBlock](https://sponsor.ajay.app/) "Отправить сегмент."

**Comment by Zalexanninev15** [comment]
Ввёл 2 правки:
https://github.com/Zalexanninev15/NoADS_RU/commit/2940c3d56dbcd21d05b70a4743dd0af9f9ce4fa3
https://github.com/Zalexanninev15/NoADS_RU/commit/f5ed53dc9ee709ee20eb50c99b76411e99b5d79b

Проверьте работает ли теперь.

**Comment by KVAnton-WEB** [comment]
Да, спасибо
