### ISSUE TITLE
Яндекс Почта

### ISSUE THREAD

**Issue by KVAnton-WEB** [Zalexanninev15/NoADS_RU#4]
Кажется сломали яндекс почту) тело письма не открывается. (какие именно фильтры - не разбирался, но где-то в вашем файле)

Вот мои фильтры, которые блокируют рекламу в Почте  (надо, наверное, тоже потестировать, но у меня пока работает)
```
mail.yandex.ru##div[data-key="box=infoline-box"] + div
mail.yandex.ru##div[data-key="view=labels"] + div
mail.yandex.ru##div[data-key="view=mail-pro-left-column-button"] + div
```

**Comment by Zalexanninev15** [comment]
Да, иногда бывает, почта ломается, но лечится это банальной перезагрузкой страницы. Попробую поискать причину проблемы. Ваши фильтры будут добавлены вместе с фиксом списка)

**Comment by Zalexanninev15** [comment]
Посмотрите, теперь работает или нет.

**Comment by Zalexanninev15** [comment]
Правка применена. Благодарю за найденный косяк и его исправление 👍
