### ISSUE TITLE
Filter is interfering with Gmail switching

### ISSUE THREAD

**Issue by rakitanc** [Zalexanninev15/NoADS_RU#7]
https://imgur.com/a/znbOPHE

uBlock Origin 1.44.4

Chrome Version 103.0.5060.114 (Official Build) (64-bit)

**Comment by Zalexanninev15** [comment]
I saw the problem, but I haven't found a solution yet.

**Comment by rakitanc** [comment]
Thanks for the reply

Have you consulted with Ublock developers on reddit..They are quite active there and cooperative. You might come up with a solution

**Comment by Zalexanninev15** [comment]
> Thanks for the reply
> 
> Have you consulted with Ublock developers on reddit..They are quite active there and cooperative. You might come up with a solution

Hello, I removed the filter that caused the display of these panels on Google pages to break (not only Gmail) https://github.com/Zalexanninev15/NoADS_RU/commit/ba91f125e1dbeaa24f039a634f56f6bcedfee749

**Comment by rakitanc** [comment]
> > Thanks for the reply
> > Have you consulted with Ublock developers on reddit..They are quite active there and cooperative. You might come up with a solution
> 
> Hello, I removed the filter that caused the display of these panels on Google pages to break (not only Gmail) [ba91f12](https://github.com/Zalexanninev15/NoADS_RU/commit/ba91f125e1dbeaa24f039a634f56f6bcedfee749)

Thanks a lot. Appreciate it mate
